version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PuppeteerLambdaPuppeteerDashAccounts"
s3_bucket = "cf-templates-deniz"
s3_prefix = "PuppeteerLambdaPuppeteerDashAccounts"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = false
confirm_changeset = true
disable_rollback = true
